name: Date

on:
  issues: 
    types: [opened, edited, deleted]
  pull_request:
    types: [ready_for_review]
  wiki:
    types: [created, edited, deleted]
  schedule:
    - cron: '* /1 * * * '
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show date
        run: date +"%m-%d-%Y %H:%M:%S"
