# This is a basic workflow to help you get started with Actions

name: hello-world

# Controls when the workflow will run
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print hello world
        run: echo Hello, world!
      - name: Show date
        run: date +"%m-%d-%Y %H:%M:%S"
