name: Services

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports: 
          - 4242:80
    steps:
      - name: Curl localhost
        run: curl -I http://0.0.0.0:4242/ | head -n 1
