name: variables

env:
  NGINX_USER: "john"
  NGINX_PASSWORD: ${{ secrets.PASSWORD }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: mrsquaare/nginx-htpasswd
        ports: 
          - 4242:80
    steps:
      - name: Curl localhost        
        run: curl -u $NGINX_USER:$NGINX_PASSWORD -I http://0.0.0.0:4242/
